% EXPORT_FEED  Write one simulation run as a JSON feed for dashboard.html
function export_feed(res, filename)
feed.meta = struct(...
    'mode',             res.mode, ...
    'ambDelay',         round(res.ambDelay, 2), ...
    'ambStops',         res.ambStops, ...
    'normalDelayB',     round(res.delayB, 2), ...
    'maxQueue',         res.maxQueue, ...
    'acceptedMsgs',     res.accepted, ...
    'rejectedMsgs',     res.rejects ...
);
feed.meta.operator = res.opEvents;
feed.meta.leadMode = res.opts.leadMode;   % 'fixed' or 'adaptive' trigger   % operator console commands (empty if none)

nSteps = numel(res.trace.t);
frames = cell(nSteps, 1);

for k = 1:nSteps
    frames{k} = struct(...
        'time',      res.trace.t(k), ...
        'ambulance', struct('x', round(res.trace.x(k), 2), 'v', round(res.trace.v(k), 2)), ...
        'junctions', struct(...
            'state',   res.trace.state(:, k).', ...
            'qA',      res.trace.qA(:, k).', ...
            'qB',      res.trace.qB(:, k).', ...
            'engaged', res.trace.engaged(:, k).', ...
            'pdir',    res.trace.pdir(:, k).' ...
        )...
    );
end
if numel(res.amb) > 1   % second (empty) ambulance: position along its own road
    for k = 1:nSteps
        frames{k}.ambulance2 = struct('active', res.trace.act2(k), 'road', res.amb(2).road, ...
            'x', round(res.trace.x2(k), 2), 'v', round(res.trace.v2(k), 2));
    end
    feed.meta.twoAmb = true;  feed.meta.emptyDelay = round(res.emptyDelay, 2);
    feed.meta.heldSecondsEmpty = res.heldSeconds(2);
end
feed.frames = frames;

jsonStr = jsonencode(feed);
fid = fopen(filename, 'w');
if fid ~= -1
    fwrite(fid, jsonStr, 'char');
    fclose(fid);
    fprintf('Exported %d simulation frames to %s\n', nSteps, filename);
else
    warning('Failed to write export file: %s', filename);
end
end
